### ISSUE TITLE
Default build fails if no static libraries present

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/siemens_to_ismrmrd#40]
By [default](https://github.com/ismrmrd/siemens_to_ismrmrd/blob/0a3af4f2555fc3288df23053932ba67fd0ba3781/CMakeLists.txt#L58) siemens_to_ismrmrd uses static libraries for Boost, but Ubuntu (debian?) doesn't include those in its boost package apparently. It would be better to check that if the static libraries are present, and if not try to find boost again without this requirement.

**Comment by IgorIzyurov** [comment]
In case the issue is still relevant:
Most probably, the problem occurs with users who have Anaconda installed. It includes h5py package, which contains libhdf5.so. library. I'm not sure about the exact problem but there seems to be the conflict of names or file paths. 
Temporarily uninstalling h5py or removing Anaconda from PATH does the trick.
