### ISSUE TITLE
Make errors ignorable

### ISSUE THREAD

**Issue by marcsous** [ismrmrd/siemens_to_ismrmrd#5]
Hi,

Thanks for making this utility. I have a sequence that produces a .dat file that always fails to convert around line 1150:

   if (xml_file_is_valid(xml_config, schema_file_name_content) <= 0)
    {
        std::cerr << "Generated XML is not valid according to the ISMRMRD schema" << std::endl;
        return -1;
    }

If I comment out the return statement (as above) then the generated file works fine for my purposes. I wonder if you could make a command-line option to ignore errors? It's not ideal but sometimes you have no way to fix the .dat files and the errors may be unimportant. Thanks!

**Comment by hansenms** [comment]
It's open source, so you can compile your own version that skips it (as you did), however, we feel that it is important to produce an XML header that is valid, not one that works fine for some purposes. I would suggest that you try to figure out what the problem is. This can be done by running the converter with the `-X` or `--debug` switch. That should dump the intermediate XML files in your local folder. You can then run xmllint to figure out why the produced XML file is not valid. So to be specific, first run your conversion:

    siemens_to_ismrmrd -f meas.dat -o test.h5 -X

That should produce 3 additional files:

```
config_buffer.xprot
processed.xml
xml_raw.xml
```

The processed.xml is the final XML file. If you run xmllint to validate that:

    xmllint --schema /usr/local/share/ismrmrd/schema/ismrmrd.xsd processed.xml

You should get some error indicating what is wrong with the XML file. If it is valid, you should get: `processed.xml validates` at the end of the dump. 

Once you figure out what the error is, you can modify the xslt stylesheet that is applied to xml_raw.xml to produce processed.xml. You can extract the existing stylesheets from the converter with the `--extract` switch. Then modify it and use `xsltproc` to generate a new XML header until it validates. Once you have a header that validates, you can use your modified stylesheet to convert your files or if it is a bug, supply the correction as a pull request and we will merge. 

Hope this helps.
