### ISSUE TITLE
nxva11b, IRIS protocol is not complete 

### ISSUE THREAD

**Issue by hanfei2000** [ismrmrd/siemens_to_ismrmrd#61]
Hi,

I am trying to convert a Siemens nxva11b raw-data to ismrmrd format and I found that many information in the IRIS protocol is not complete. 

The attached snippet is from "xml_raw.xml"
 using the -X option. Infomation like "IRIS/DERIVED/phaseOversampling", "IRIS/DERIVED/imageColumns" are missing

Thank you,
Fei

![Capture](https://user-images.githubusercontent.com/20009860/81464373-fa042c00-9175-11ea-8de1-1a122e55eaf4.PNG)

**Comment by RitiP** [comment]
Hello Fei,

Did you solve this issue? I'm facing a similar situation and have no idea why the code is skipping that information.

**Comment by hansenms** [comment]
I am closing this for now due to inactivity. If this is still an issue, please reopen. If it is a bug, please provide steps to reproduce (including a data file) and also clear description of what the expected result is and what you are actually seeing. There are some fields in the Siemens headers that are there in some versions but not in others. That is why we have a combination of parameter maps and stylesheets to allow you to navigate this. Again, if you need help with this, let us know and we will try to take a look.
